<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ApiTemplate.EventBus.Domain.Core</RootNamespace>
  </PropertyGroup>

  <!-- No dependencies - pure domain types -->

</Project>
