name: CI/CD Pipeline

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Show current directory
        run: pwd # Print the current working directory to ensure we're in the right place

      - name: List files after checkout
        run: ls -R # List files in the directory after checking out the code

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push web Docker image
        run: |
          IMAGE_NAME=1238456anrd/web
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG -f ApiTemplate.Presentation.Web/Dockerfile .
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your region

      - name: Register new ECS task definition
        id: task-def
        run: |
          TASK_DEFINITION=$(cat <<EOF
          {
            "family": "my-app-task",
            "networkMode": "awsvpc",
            "containerDefinitions": [
              {
                "name": "web",
                "image": "1238456anrd/web:${{ github.sha }}",
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 80,
                    "protocol": "tcp"
                  }
                ]
              },
              {
                "name": "elasticsearch",
                "image": "docker.elastic.co/elasticsearch/elasticsearch:7.9.3",
                "essential": true,
                "memory": 1024,
                "cpu": 512,
                "portMappings": [
                  {
                    "containerPort": 9200,
                    "protocol": "tcp"
                  }
                ],
                "environment": [
                  {
                    "name": "discovery.type",
                    "value": "single-node"
                  }
                ]
              },
              {
                "name": "ms-sql-server",
                "image": "mcr.microsoft.com/mssql/server:2017-latest-ubuntu",
                "essential": true,
                "memory": 2048,
                "cpu": 1024,
                "portMappings": [
                  {
                    "containerPort": 1433,
                    "protocol": "tcp"
                  }
                ],
                "environment": [
                  {
                    "name": "ACCEPT_EULA",
                    "value": "Y"
                  },
                  {
                    "name": "SA_PASSWORD",
                    "value": "Passw0rd123"
                  }
                ]
              },
              {
                "name": "kibana",
                "image": "docker.elastic.co/kibana/kibana:7.9.3",
                "essential": true,
                "memory": 512,
                "cpu": 256,
                "portMappings": [
                  {
                    "containerPort": 5601,
                    "protocol": "tcp"
                  }
                ],
                "environment": [
                  {
                    "name": "ELASTICSEARCH_HOSTS",
                    "value": "http://elasticsearch:9200"
                  }
                ]
              },
              {
                "name": "apm-server",
                "image": "docker.elastic.co/apm/apm-server:7.9.3",
                "essential": false,
                "memory": 512,
                "cpu": 256,
                "portMappings": [
                  {
                    "containerPort": 8200,
                    "protocol": "tcp"
                  }
                ],
                "environment": [
                  {
                    "name": "output.elasticsearch.hosts",
                    "value": "[\"http://elasticsearch:9200\"]"
                  },
                  {
                    "name": "apm-server.kibana.enabled",
                    "value": "true"
                  },
                  {
                    "name": "apm-server.kibana.host",
                    "value": "http://kibana:5601"
                  }
                ]
              }
            ],
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "4096",
            "memory": "8192",
            "executionRoleArn": "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecsTaskExecutionRole"
          }
          EOF
          )

          echo "$TASK_DEFINITION" > task-def.json
          aws ecs register-task-definition --cli-input-json file://task-def.json

      - name: Update ECS service
        run: |
          CLUSTER_NAME=ApiTemplateCluster
          SERVICE_NAME=ApiTemplateService
          TASK_DEFINITION_ARN=$(aws ecs describe-task-definition --task-definition my-app-task | jq -r '.taskDefinition.taskDefinitionArn')
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --task-definition $TASK_DEFINITION_ARN --force-new-deployment
