name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: docker --version

      - name: Clean up Docker (if any previous containers are running)
        run: docker system prune -af

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore ApiTemplate.sln

      - name: Test
        run: dotnet test ApiTemplate.sln
