version: '3.4'

services:
  web:
    build:
      context: ../
      dockerfile: Web\Dockerfile
    ports:
        - "8080:80"
    environment:
        UseDb: "4" # docker env
        ASPNETCORE_ENVIRONMENT: "Production"
        DOTNET_DockerDb: "Server=ms-sql-server,1433;Database=webapi;User=SA;Password=Passw0rd123;MultipleActiveResultSets=True;TrustServerCertificate=True;"

  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    ports:
        - "1453:1433"
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: Passw0rd123
        MSSQL_PID: Express
